### ISSUE TITLE
Datasets?

### ISSUE THREAD

**Issue by evolvedmicrobe** [drisso/zinb_analysis#4]
Is there a location where we can get the data used in the paper? Trying to reproduce, it looks like some of the files, e.g. `../sims/datasets/patel/glioblastoma_raw_rnaseq_SCandbulk_counts_withannots.txt"` aren't in the repository.

Thanks for any help,
N
`

**Comment by drisso** [comment]
Hi @evolvedmicrobe 
As github is not the best way to store large files, we did not include the datasets in the repo.

@fperraudeau do you remember from where we downloaded this file (or do you still have a local copy)? We should either add a link to the source in the README or add the files as a git lfs file.

I'm almost sure the source is the supplementary file that you can find at this page: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE57872

But @fperraudeau should correct me if I'm wrong.

**Comment by drisso** [comment]
Ok, sorry scratch my last sentence. We reprocessed the glioblastoma data, so it's not the matrix that you find on GEO. Let us look into the best way of making it publicly available and we will.

**Comment by evolvedmicrobe** [comment]
Hi @drisso,

Thanks for the quick response.  I was able to get some of the datasets from Geo and the other R packages, so am off and running on the datasets and am now playing around with some data that has better opportunities for making use of the regression models than the glioblastoma one.

I think it's likely others might benefit from having the data more easily available, but as my current needs are met, please don't feel any urge to do it on my account now.

Warm wishes,
Nigel
