### ISSUE TITLE
Patel counts

### ISSUE THREAD

**Issue by twillis209** [drisso/zinb_analysis#6]
Hello again

Would it be possible for you to make available the count data you used for your downstream analysis of the Patel data?

This was raised in issue #4. As I understand it, the Patel raw data were reprocessed with TopHat and htseq, rather than using the counts Patel et al. made available on GSE. You proposed making the counts available in a reply on issue #4, but it seems the user who raised the issue was able to perform their own quantification of the raw reads and thus no longer required them.

Please let me know if it is inappropriate to pester you for this sort of information so long after publication. I am a Master's student and not yet fully au fait with the conventions of the field as regards 'technical support' for the reproduction of a paper. I am appreciative of the fact that this repo exists in the first place.

**Comment by drisso** [comment]
Hi,

it's totally fine to ask these questions. Please, forgive me if I don't respond right away but in this period it is particularly challenging to keep up with everything. 

I just added a file with the data at https://github.com/drisso/zinb_analysis/blob/master/real_data/GSE57872_GBM_data_matrix.txt.gz

I am almost sure that these are the data that we used for the paper, but in case you see some discrepancies please re-open this and I will double check.

**Comment by twillis209** [comment]
Dear Davide

Thank you for that. I have diff'd that file with the one I downloaded from GSE and found no difference.

Reading the methods section of your paper, I understand that you downloaded the Patel reads and aligned them with TopHat then quantified with htseq-count. Your approach differed from that used by Patel ( who used Bowtie+RSEM), so it would be helpful for me in reproducing your 2018 to have your own counts rather than those of Patel (if you still have access to them).

**Comment by drisso** [comment]
You're right. Sorry, but that was the only "patel" file that I found sitting around in my laptop. I'm afraid I will have to dig deeper to find the right file, but I'm tagging @fperraudeau @sgribkova just in case they have the file and they are able to share it?

**Comment by drisso** [comment]
I **think** I found the correct data. It's at https://github.com/drisso/zinb_analysis/blob/master/real_data/Patel.zip.

@twillis209 please have a look and let me know if you're able to reproduce the analysis with these data.

**Comment by twillis209** [comment]
Looks good to me, thank you very much!
